---
- name: get users list in host
  hosts: all
  tasks:
    - name: /etc/passwd에서 사용자 이름 추출
      command: cut --delimiter=':' --fields=1 /etc/passwd
      register: usernames_result

    - name: usernames_result 변수를 디버깅으로 표시
      debug: 
        var: usernames_result
